### ISSUE TITLE
Adapter bleibt nicht Grün (Gelöst)

### ISSUE THREAD

**Issue by Deathmeat** [TA2k/ioBroker.weishaupt-wem#14]
Hallo Zusammen,
wenn ich den Adapter Starte ruft er kurz die Werte ab und springt dann auf rot.
Installiert im Docker auf einer Synology NAS.

Node.js v14.18.3
NPM 8.3.1

Im Report steht folgende Fehlermeldung.  

weishaupt-wem.0 | 2022-01-15 11:58:48.202 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason -- | -- | -- | --
weishaupt-wem.0 | 2022-01-15 11:58:48.199 | info | terminating
weishaupt-wem.0 | 2022-01-15 11:58:48.192 | info | cleaned everything up...
weishaupt-wem.0 | 2022-01-15 11:58:48.137 | error | The id "Keller XXXXXX." is invalid. Ids are not allowed to end in "."
weishaupt-wem.0 | 2022-01-15 11:58:48.136 | error | Error: The id "Keller XXXXX." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:537:23) at WeishauptWem.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3387:17) at Request._callback (/opt/iobroker/node_modules/iobroker.weishaupt-wem/main.js:330:30) at Request.self.callback (/opt/iobroker/node_modules/iobroker.weishaupt-wem/node_modules/request/request.js:185:22) at Request.emit (events.js:400:28) at Request.<anonymous> (/opt/iobroker/node_modules/iobroker.weishaupt-wem/node_modules/request/request.js:1154:10) at Request.emit (events.js:400:28) at Gunzip.<anonymous> (/opt/iobroker/node_modules/iobroker.weishaupt-wem/node_modules/request/request.js:1076:12) at Object.onceWrapper (events.js:519:28) at Gunzip.emit (events.js:400:28)
weishaupt-wem.0 | 2022-01-15 11:58:48.133 | error | unhandled promise rejection: The id "Keller XXXXX." is invalid. Ids are not allowed to end in "."
weishaupt-wem.0 | 2022-01-15 11:58:48.132 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Comment by TA2k** [comment]
Bitte via github installieren und schauen ob das problem weg ist

**Comment by Deathmeat** [comment]
Den Fehler habe ich gerade behoben bekommen. Ich habe den Anlagen Namen auf der WEM Webseite geändert. 
Vorher war der Name "Keller Schm.../ B...b...str." und jetzt heißt sie einfach Heizung. (die ... habe ich aus Datenschutz gründen hier verwendet.)

**Comment by TA2k** [comment]
Aber es war vorher ein  Punkt enthalten oder

**Comment by Deathmeat** [comment]
Ja bei B...b...str.
