### ISSUE TITLE
Fehler in 0.0.14

### ISSUE THREAD

**Issue by etofi** [TA2k/ioBroker.weishaupt-wem#18]
Hallo zusammen,
ich habe gerade das Update von 0.0.13 auf 0.0.14 installiert.
Leider wirft es mir jetzt laufend Fehlermeldung und es werden auch nicht mehr alle Datenpunkte ausgelesen.

`AxiosError: Request failed with status code 400`

`{"Status":3000,"Message":"Mindestens ein erforderlicher Parameter fehlt","DetailMessages":[]}`

**Comment by TA2k** [comment]
bitte ml github version checken habe das app feature in eine separate Einstellung ausgeleagert

**Comment by etofi** [comment]
Wie installiert man die Github Version?

**Comment by TA2k** [comment]
Unter Adapter 
<img width="60" alt="image" src="https://user-images.githubusercontent.com/1307684/231551281-589358d2-f12d-4c5c-b460-ce8f6a1965ac.png">
<img width="74" alt="image" src="https://user-images.githubusercontent.com/1307684/231551327-f2e81ab6-511c-42a9-adc6-41233c317a20.png">

**Comment by TA2k** [comment]
Lieber nicht anscheinend geht bei dir die Android App nicht aber dazu bräuchte ich ein längeren log

**Comment by etofi** [comment]
Also ich verwende die Android App und die tut auch. Aber halt auf dem Handy und ioBroker läuft auf Docker in meiner NAS.
Ich kann Dir gerne nen Log zur Verfügung stellen wenn ich Samstag wieder daheim bin. 
Ach übrigens ich vermisse noch immer Datenpunkte. Bisher hatte ich Z.B. DreiwegeventilinternWE0

**Comment by TA2k** [comment]
es wurde eigentlich nichts geändert außer app support

**Comment by etofi** [comment]
Komisch. Dann wohl doch nen Log. Welches Log Level soll ich verwenden?

**Comment by TA2k** [comment]
debug und via mail dann
tombox2020@gmail.com

**Comment by etofi** [comment]
Hab App Daten an gemacht und die Mail mit Debug Log geschickt.

**Comment by TA2k** [comment]
gefixt mit 0.0.15
